services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: restream-app
        environment:
            NODE_ENV: production
            PORT: 3030
            MEDIAMTX_INTERNAL_HOST: mediamtx
        ports:
            - '3030:3030'
        volumes:
            - ./src/config/restream.json:/app/src/config/restream.json:ro
        depends_on:
            - mediamtx

    mediamtx:
        image: bluenviron/mediamtx:1
        container_name: mediamtx
        ports:
            - '1935:1935' # RTMP ingest
            - '8554:8554' # RTSP ingest and read
            - '8890:8890/udp' # SRT ingest
            - '8888:8888' # HTTP interface / HLS
            - '8889:8889' # WebRTC HTTP
            - '8189:8189/udp' # WebRTC ICE
            - '8189:8189/tcp' # WebRTC ICE
            - '9997:9997' # API
        volumes:
            - ./infra/mediamtx.yml:/mediamtx.yml

    nginx-rtmp:
        image: tiangolo/nginx-rtmp:latest
        container_name: nginx-rtmp
        ports:
            - '1936:1935'
            - '8081:80'
        volumes:
            - ./infra/nginx-rtmp.conf:/etc/nginx/nginx.conf:ro
