//! `cargo xtask setup-skills`: local Claude Code skill registrations for the
//! canonical, agent-neutral skills in `docs/agent-guidance/skills/`.
//!
//! `.claude/` is gitignored; run once per clone or worktree
//! (`scripts/agent/worktree.sh` runs it). Idempotent: re-run after adding a
//! skill or editing skill frontmatter. The default writes one small shim per
//! skill; `--symlink` links `.claude/skills` at the canonical directory
//! instead (no drift, but relies on the loader following symlinks).

use std::fs;
use std::path::Path;

use crate::StepResult;

const CANON: &str = "docs/agent-guidance/skills";
const DEST: &str = ".claude/skills";
const SHIM_MARKER: &str = "generated by cargo xtask setup-skills";
/// Marker of shims written before the port; still ours to replace or prune.
const OLD_SHIM_MARKER: &str = "generated by scripts/agent/setup-skills.sh";

pub(crate) fn setup_skills(args: &[&str]) -> StepResult {
    let symlink = match args {
        [] => false,
        ["--symlink"] => true,
        _ => return Err("usage: cargo xtask setup-skills [--symlink]".into()),
    };
    if !Path::new(CANON).is_dir() {
        return Err(format!("canonical skills not found at {CANON}"));
    }
    let dest = Path::new(DEST);
    if symlink {
        if dest.exists() && !dest.is_symlink() {
            // Refuse to delete anything this command did not generate.
            let stray = foreign_skill_files(dest);
            if !stray.is_empty() {
                return Err(format!(
                    "{DEST} contains files not generated by this command; move them first:\n{}",
                    stray.join("\n")
                ));
            }
            fs::remove_dir_all(dest).map_err(|error| format!("cannot remove {DEST}: {error}"))?;
        }
        fs::create_dir_all(".claude").map_err(|error| format!("cannot create .claude: {error}"))?;
        let _ = fs::remove_file(dest);
        std::os::unix::fs::symlink("../docs/agent-guidance/skills", dest)
            .map_err(|error| format!("cannot link {DEST}: {error}"))?;
        println!("linked {DEST} -> {CANON}");
        return Ok(());
    }

    if dest.is_symlink() {
        fs::remove_file(dest).map_err(|error| format!("cannot remove {DEST}: {error}"))?;
    }
    fs::create_dir_all(dest).map_err(|error| format!("cannot create {DEST}: {error}"))?;
    let mut count = 0;
    for name in sorted_dirs(Path::new(CANON)) {
        let Ok(body) = fs::read_to_string(Path::new(CANON).join(&name).join("SKILL.md")) else {
            continue;
        };
        let Some(description) = shim_description(&name, &body) else {
            eprintln!("warn: skip {name} (no description: frontmatter)");
            continue;
        };
        let dir = dest.join(&name);
        fs::create_dir_all(&dir)
            .map_err(|error| format!("cannot create {}: {error}", dir.display()))?;
        fs::write(dir.join("SKILL.md"), shim(&name, &description))
            .map_err(|error| format!("cannot write shim for {name}: {error}"))?;
        count += 1;
    }
    for name in sorted_dirs(dest) {
        let shim = dest.join(&name).join("SKILL.md");
        let ours = fs::read_to_string(&shim).is_ok_and(|text| is_generated(&text));
        if ours && !Path::new(CANON).join(&name).join("SKILL.md").is_file() {
            fs::remove_dir_all(dest.join(&name))
                .map_err(|error| format!("cannot prune {name}: {error}"))?;
            println!("pruned stale shim: {name}");
        }
    }
    println!("generated {count} Claude Code skill shims in {DEST}/");
    Ok(())
}

fn is_generated(text: &str) -> bool {
    text.contains(SHIM_MARKER) || text.contains(OLD_SHIM_MARKER)
}

/// The shim's `description:` line: double-quoted for valid YAML unless the
/// canonical value already contains double quotes.
fn shim_description(name: &str, body: &str) -> Option<String> {
    let line = body.lines().find(|line| line.starts_with("description:"))?;
    let value = line
        .strip_prefix("description: ")
        .unwrap_or(&line["description:".len()..]);
    if !value.contains('"') {
        return Some(format!("description: \"{value}\""));
    }
    if value.contains(": ") {
        eprintln!("warn: {name} description mixes double quotes and ': '; check the shim parses");
    }
    Some(line.to_owned())
}

fn shim(name: &str, description: &str) -> String {
    format!(
        "---\nname: {name}\n{description}\n---\n\nClaude Code registration shim ({SHIM_MARKER}).\n\
         The canonical, agent-neutral skill lives at\n\
         [docs/agent-guidance/skills/{name}/SKILL.md](../../../docs/agent-guidance/skills/{name}/SKILL.md).\n\n\
         Read that file and apply the relevant guidance within the user's requested scope and existing authorization.\n"
    )
}

fn sorted_dirs(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|entry| entry.path().is_dir())
        .filter_map(|entry| entry.file_name().into_string().ok())
        .collect();
    names.sort();
    names
}

/// `SKILL.md` files under `dir` that lack the generated-shim marker.
fn foreign_skill_files(dir: &Path) -> Vec<String> {
    sorted_dirs(dir)
        .into_iter()
        .map(|name| dir.join(name).join("SKILL.md"))
        .filter(|path| path.is_file())
        .filter(|path| !fs::read_to_string(path).is_ok_and(|text| is_generated(&text)))
        .map(|path| path.display().to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn descriptions_are_quoted_unless_already_quoted() {
        let plain = "---\nname: x\ndescription: Use for X: things\n---\n";
        assert_eq!(
            shim_description("x", plain).as_deref(),
            Some("description: \"Use for X: things\"")
        );
        let quoted = "description: Say \"hi\"\n";
        assert_eq!(
            shim_description("x", quoted).as_deref(),
            Some("description: Say \"hi\"")
        );
        assert_eq!(shim_description("x", "name: x\n"), None);
    }

    #[test]
    fn shim_has_frontmatter_and_points_at_the_canonical_skill() {
        let text = shim("critic", "description: \"Review\"");
        assert!(text.starts_with("---\nname: critic\ndescription: \"Review\"\n---\n"));
        assert!(text.contains("(../../../docs/agent-guidance/skills/critic/SKILL.md)"));
        assert!(is_generated(&text));
    }
}
