#!/usr/bin/env bash
# TX-only substrate lane: a disposable dummy netdev that discards what it
# receives, with the destination prefix routed through it.
#
# This lane exists to separate sender-side cost from peer-side cost. A veth pair
# delivers into a peer's receive path (and, without RPS, into the sender's own
# CPU), so a veth lane cannot say what one core can *submit*. A dummy device has
# no peer, no receiver process and no RX protocol path: what remains is the
# sender's own UDP/IP stack, route lookup and qdisc/driver transmit, and the
# netdev's TX counters account for every datagram that left.
#
# This is a sender-side kernel-stack upper bound. It is not physical-NIC
# qualification (no DMA, no IRQ placement, no line-rate backpressure) and must
# never be reported as one.
#
# Usage:
#   sudo scripts/harness/dummy-lane.sh up [--cpus <sender> <harness>]
#   scripts/harness/dummy-lane.sh start-sender <variant> [extra env assignments]
#   scripts/harness/dummy-lane.sh status
#   sudo scripts/harness/dummy-lane.sh down
set -euo pipefail

DEV="${WI3_TX_DEV:-wi3tx0}"
PREFIX="${WI3_TX_PREFIX:-10.53.0.0/16}"
ENV_FILE="${WI3_TX_ENV_FILE:-$(pwd)/.local/artifacts/wi3-dummy-lane/wi3-dummy-lane.env}"
SENDER_BIN="${WI3_TX_BIN:-$(pwd)/target/bench/test_harness}"

usage() {
  sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
}

require_root() {
  [[ "$(id -u)" -eq 0 ]] || { echo "[dummy-lane] needs root (ip link/route)" >&2; exit 2; }
}

default_cpu_masks() {
  local nproc
  nproc="$(nproc)"
  if [[ "$nproc" -ge 4 ]]; then
    echo "0 1-$((nproc - 1))"
  else
    echo "0 1"
  fi
}

cmd_up() {
  local sender_mask harness_mask
  if [[ "${1:-}" == "--cpus" ]]; then
    sender_mask="${2:?--cpus needs two masks}"
    harness_mask="${3:?--cpus needs two masks}"
  else
    read -r sender_mask harness_mask <<<"$(default_cpu_masks)"
  fi
  require_root
  mkdir -p "$(dirname "$ENV_FILE")"

  if ip link show "$DEV" >/dev/null 2>&1; then
    echo "[dummy-lane] ${DEV} already exists; run 'down' first" >&2
    exit 2
  fi
  # A peer lane owning the same prefix would silently absorb the traffic, and a
  # veth peer in this lane is exactly what the lane exists to exclude.
  if ip route show "$PREFIX" | grep -q .; then
    echo "[dummy-lane] ${PREFIX} already has a route; tear the other lane down first:" >&2
    ip route show "$PREFIX" >&2
    exit 2
  fi

  ip link add "$DEV" type dummy
  ip link set "$DEV" up
  ip link set "$DEV" arp off
  ip route add "$PREFIX" dev "$DEV"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/harness/dummy-lane.sh — source before a TX-only run.
export SUBSTRATE_TX_NETDEV=${DEV}
export SUBSTRATE_SENDER_CPUS=${sender_mask}
export SUBSTRATE_HARNESS_CPUS=${harness_mask}
export SUBSTRATE_DEST_BASE=10.53.1.1
export SUBSTRATE_DEST_COUNT=1000
export SUBSTRATE_DEST_PORT=9000
EOF

  echo "[dummy-lane] up: ${DEV} discarding ${PREFIX}; sender cpu ${sender_mask}, harness cpus ${harness_mask}"
  echo "[dummy-lane] env written to ${ENV_FILE}"
  echo "[dummy-lane] run: source ${ENV_FILE} && scripts/harness/dummy-lane.sh start-sender <sendto|compio|io-uring>"
}

# Start one measurement arm on the lane: the harness is pinned to the harness
# CPUs and the sender thread moves itself to the sender CPU.
cmd_start_sender() {
  local variant="${1:?start-sender needs a variant}"
  shift || true
  [[ -f "$ENV_FILE" ]] || { echo "[dummy-lane] run 'up' first (${ENV_FILE} missing)" >&2; exit 2; }
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  [[ -x "$SENDER_BIN" ]] || { echo "[dummy-lane] harness binary missing: ${SENDER_BIN}" >&2; exit 2; }
  local work_dir="${WORK_DIR:-.local/artifacts/wi3-dummy-${variant}}"
  # shellcheck disable=SC2086
  env SUBSTRATE_VARIANT="$variant" "$@" WORK_DIR="$work_dir" \
    taskset -c "${SUBSTRATE_HARNESS_CPUS}" "$SENDER_BIN" substrate-pps --no-netns
}

cmd_status() {
  ip -details link show "$DEV" 2>/dev/null | head -2 || echo "[dummy-lane] ${DEV} absent"
  ip route show "$PREFIX" || true
  local stats="/sys/class/net/${DEV}/statistics"
  if [[ -r "${stats}/tx_packets" ]]; then
    echo "[dummy-lane] tx_packets=$(cat "${stats}/tx_packets") tx_bytes=$(cat "${stats}/tx_bytes")"
  fi
}

cmd_down() {
  require_root
  ip route del "$PREFIX" dev "$DEV" 2>/dev/null || true
  ip link del "$DEV" 2>/dev/null || true
  rm -f "$ENV_FILE"
  echo "[dummy-lane] down: ${DEV} removed"
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  start-sender) shift; cmd_start_sender "$@" ;;
  status) cmd_status ;;
  down) cmd_down ;;
  *) usage; exit 2 ;;
esac
