#!/usr/bin/env bash
# Namespace-separated benchmark topology for the single-host development lane.
#
# Creates a veth pair with one end in a dedicated network namespace so a sink
# peer has its own network stack, socket tables, routing and qdisc path instead
# of the loopback special case, and writes the environment a run needs:
#
#   scripts/harness/veth-topology.sh up [--cpus <restream> <sink>]
#   scripts/harness/veth-topology.sh down
#   scripts/harness/veth-topology.sh status
#
# The generated env file (`<work-dir>/wi3-topology.env`) pins the peer host,
# both peer ports and both CPU masks; the harness records the *observed* masks
# (restream's Cpus_allowed_list, each peer's /state mask) in the artifact.
#
# This is development qualification, not NIC qualification: a veth path says
# nothing about PCIe/DMA, hardware queues, IRQ/NAPI placement, offloads or
# physical-link behaviour. Those belong to the multi-host lane.
set -euo pipefail

ROOT_DIR="${RESTREAM_REPO_ROOT:-$(git rev-parse --show-toplevel)}"
NETNS="${WI3_NETNS:-wi3-sink}"
VETH_HOST="${WI3_VETH_HOST:-veth-wi3}"
VETH_PEER="${WI3_VETH_PEER:-veth-wi3p}"
HOST_ADDR="${WI3_HOST_ADDR:-10.53.0.1/24}"
PEER_ADDR="${WI3_PEER_ADDR:-10.53.0.2/24}"
SRT_PORT="${WI3_SRT_PORT:-8891}"
STATE_PORT="${WI3_STATE_PORT:-9997}"
WORK_DIR="${WORK_DIR:-$ROOT_DIR/.local/artifacts/wi3-topology}"
ENV_FILE="${WI3_TOPOLOGY_ENV:-$WORK_DIR/wi3-topology.env}"

usage() {
  cat >&2 <<EOF
usage:
  scripts/harness/veth-topology.sh up [--cpus <restream-mask> <sink-mask>]
  scripts/harness/veth-topology.sh down
  scripts/harness/veth-topology.sh status

env overrides: WI3_NETNS WI3_VETH_HOST WI3_VETH_PEER WI3_HOST_ADDR WI3_PEER_ADDR
               WI3_SRT_PORT WI3_STATE_PORT WORK_DIR WI3_TOPOLOGY_ENV
EOF
}

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "[veth-topology] needs root (or CAP_NET_ADMIN) to create namespaces" >&2
    exit 2
  fi
}

netns_exec() {
  ip netns exec "$NETNS" "$@"
}

# Default partition: half the CPUs for the measured datapath, the rest for the
# receiver, so the sink cannot consume the core under measurement.
default_cpu_masks() {
  local cpus
  cpus=$(nproc)
  if (( cpus < 4 )); then
    echo "[veth-topology] at least 4 CPUs are needed to partition sender and receiver" >&2
    exit 2
  fi
  local restream_end=$(( cpus / 2 - 1 ))
  local sink_start=$(( cpus / 2 ))
  echo "0-${restream_end} ${sink_start}-$(( cpus - 1 ))"
}

cmd_up() {
  local restream_mask sink_mask
  if [[ "${1:-}" == "--cpus" ]]; then
    restream_mask="${2:?--cpus needs two masks}"
    sink_mask="${3:?--cpus needs two masks}"
  else
    read -r restream_mask sink_mask <<<"$(default_cpu_masks)"
  fi
  require_root
  mkdir -p "$WORK_DIR"

  if ip netns list | grep -q "^${NETNS}\b"; then
    echo "[veth-topology] namespace ${NETNS} already exists; run 'down' first" >&2
    exit 2
  fi
  ip netns add "$NETNS"
  ip link add "$VETH_HOST" type veth peer name "$VETH_PEER"
  ip link set "$VETH_PEER" netns "$NETNS"
  ip addr add "$HOST_ADDR" dev "$VETH_HOST"
  ip link set "$VETH_HOST" up
  netns_exec ip addr add "$PEER_ADDR" dev "$VETH_PEER"
  netns_exec ip link set "$VETH_PEER" up
  netns_exec ip link set lo up

  # Keep the veth path out of the host's forwarding/NAT rules.
  sysctl -qw "net.ipv4.conf.${VETH_HOST}.forwarding=0" || true

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/harness/veth-topology.sh — source before a benchmark run.
export RESTREAM_BENCH_TOPOLOGY=netns-veth
export RESTREAM_BENCH_NETNS=${NETNS}
export RESOURCE_SWEEP_SRT_PEER_HOSTS=${PEER_ADDR%%/*}
export MTX_SRT=${SRT_PORT}
export MTX_API=${STATE_PORT}
export RESTREAM_CPUSET=${restream_mask}
export SRT_SINK_CPUSET=${sink_mask}
EOF

  echo "[veth-topology] up: ${VETH_HOST} $(echo "$HOST_ADDR" | cut -d/ -f1) <-> ${NETNS}:${VETH_PEER} $(echo "$PEER_ADDR" | cut -d/ -f1)"
  echo "[veth-topology] restream cpus ${restream_mask}, sink cpus ${sink_mask}"
  echo "[veth-topology] env written to ${ENV_FILE}"
  cat <<EOF
[veth-topology] run the peer inside the namespace:
  source ${ENV_FILE}
  taskset -c \${SRT_SINK_CPUSET} ip netns exec ${NETNS} \\
    SRT_SINK_PORTS=${SRT_PORT} SRT_SINK_STATE_PORT=${STATE_PORT} \\
    target/bench/test_harness srt-sink --no-netns
EOF
}

cmd_down() {
  require_root
  if ip netns list | grep -q "^${NETNS}\b"; then
    ip netns del "$NETNS"
  fi
  ip link del "$VETH_HOST" 2>/dev/null || true
  rm -f "$ENV_FILE"
  echo "[veth-topology] down: ${NETNS} and ${VETH_HOST} removed"
}

cmd_status() {
  echo "[veth-topology] netns:"
  ip netns list | sed 's/^/  /' || true
  echo "[veth-topology] ${VETH_HOST}:"
  ip -brief addr show "$VETH_HOST" 2>/dev/null | sed 's/^/  /' || echo "  absent"
  echo "[veth-topology] env file: ${ENV_FILE}"
  [[ -f "$ENV_FILE" ]] && sed 's/^/  /' "$ENV_FILE" || echo "  absent"
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  down) cmd_down ;;
  status) cmd_status ;;
  *) usage; exit 2 ;;
esac
