#!/usr/bin/env bash
# Namespace-separated benchmark topology for the single-host development lane.
#
# Creates a veth pair with one end in a dedicated network namespace so a sink
# peer has its own network stack, socket tables, routing and qdisc path instead
# of the loopback special case, and writes the environment a run needs:
#
#   scripts/harness/veth-topology.sh up [--cpus <restream> <sink>]
#   scripts/harness/veth-topology.sh down
#   scripts/harness/veth-topology.sh status
#
# The generated env file (`<work-dir>/wi3-topology.env`) pins the peer host,
# both peer ports and both CPU masks; the harness records the *observed* masks
# (restream's Cpus_allowed_list, each peer's /state mask) in the artifact.
#
# This is development qualification, not NIC qualification: a veth path says
# nothing about PCIe/DMA, hardware queues, IRQ/NAPI placement, offloads or
# physical-link behaviour. Those belong to the multi-host lane.
set -euo pipefail

ROOT_DIR="${RESTREAM_REPO_ROOT:-$(git rev-parse --show-toplevel)}"
NETNS="${WI3_NETNS:-wi3-sink}"
VETH_HOST="${WI3_VETH_HOST:-veth-wi3}"
VETH_PEER="${WI3_VETH_PEER:-veth-wi3p}"
# A /16 keeps a whole destination prefix local inside the namespace, so a
# benchmark can address 1000 distinct destinations while one wildcard drain
# socket receives them all.
# Destination prefix the namespace accepts as local (see the route added below):
# a benchmark addresses 1000 distinct destinations inside it while one wildcard
# drain socket receives them all. Both ends are /32 addresses so the prefix is
# reached through the peer as a gateway rather than by resolving 1000
# neighbours.
WI3_DEST_PREFIX="${WI3_DEST_PREFIX:-10.53.0.0/16}"
HOST_ADDR="${WI3_HOST_ADDR:-10.53.0.1/32}"
PEER_ADDR="${WI3_PEER_ADDR:-10.53.0.2/32}"
SRT_PORT="${WI3_SRT_PORT:-8891}"
STATE_PORT="${WI3_STATE_PORT:-9997}"
WORK_DIR="${WORK_DIR:-$ROOT_DIR/.local/artifacts/wi3-topology}"
ENV_FILE="${WI3_TOPOLOGY_ENV:-$WORK_DIR/wi3-topology.env}"

usage() {
  cat >&2 <<EOF
usage:
  scripts/harness/veth-topology.sh up [--cpus <restream-mask> <sink-mask>]
  scripts/harness/veth-topology.sh start-peer [srt-sink|udp-drain]
  scripts/harness/veth-topology.sh down
  scripts/harness/veth-topology.sh status

env overrides: WI3_NETNS WI3_VETH_HOST WI3_VETH_PEER WI3_HOST_ADDR WI3_PEER_ADDR
               WI3_SRT_PORT WI3_STATE_PORT WORK_DIR WI3_TOPOLOGY_ENV
EOF
}

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "[veth-topology] needs root (or CAP_NET_ADMIN) to create namespaces" >&2
    exit 2
  fi
}

netns_exec() {
  ip netns exec "$NETNS" "$@"
}

# Default partition: half the CPUs for the measured datapath, the rest for the
# receiver, so the sink cannot consume the core under measurement.
default_cpu_masks() {
  local cpus
  cpus=$(nproc)
  if (( cpus < 4 )); then
    echo "[veth-topology] at least 4 CPUs are needed to partition sender and receiver" >&2
    exit 2
  fi
  local restream_end=$(( cpus / 2 - 1 ))
  local sink_start=$(( cpus / 2 ))
  echo "0-${restream_end} ${sink_start}-$(( cpus - 1 ))"
}

cmd_up() {
  local restream_mask sink_mask
  if [[ "${1:-}" == "--cpus" ]]; then
    restream_mask="${2:?--cpus needs two masks}"
    sink_mask="${3:?--cpus needs two masks}"
  else
    read -r restream_mask sink_mask <<<"$(default_cpu_masks)"
  fi
  require_root
  mkdir -p "$WORK_DIR"

  if ip netns list | grep -q "^${NETNS}\b"; then
    echo "[veth-topology] namespace ${NETNS} already exists; run 'down' first" >&2
    exit 2
  fi
  ip netns add "$NETNS"
  ip link add "$VETH_HOST" type veth peer name "$VETH_PEER"
  ip link set "$VETH_PEER" netns "$NETNS"
  ip addr add "$HOST_ADDR" dev "$VETH_HOST"
  ip link set "$VETH_HOST" up
  netns_exec ip addr add "$PEER_ADDR" dev "$VETH_PEER"
  netns_exec ip link set "$VETH_PEER" up
  netns_exec ip link set lo up
  # Point-to-point addressing: only the peer address needs resolution, and the
  # destination prefix is routed through it.
  ip route add "$PEER_ADDR" dev "$VETH_HOST"
  ip route add "$WI3_DEST_PREFIX" via "${PEER_ADDR%%/*}" dev "$VETH_HOST"
  netns_exec ip route add "$HOST_ADDR" dev "$VETH_PEER"

  # The namespace accepts the whole destination prefix as local, so packets
  # addressed to any of the 1000 destinations are delivered to its sockets.
  netns_exec ip route add local "$WI3_DEST_PREFIX" dev "$VETH_PEER"
  echo "[veth-topology] namespace treats ${WI3_DEST_PREFIX} as local"

  # Keep the veth path out of the host's forwarding/NAT rules.
  sysctl -qw "net.ipv4.conf.${VETH_HOST}.forwarding=0" || true

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/harness/veth-topology.sh — source before a benchmark run.
export RESTREAM_BENCH_TOPOLOGY=netns-veth
export RESTREAM_BENCH_NETNS=${NETNS}
export RESOURCE_SWEEP_SRT_PEER_HOSTS=${PEER_ADDR%%/*}
export WI3_DEST_PREFIX=${WI3_DEST_PREFIX}
export MTX_SRT=${SRT_PORT}
export MTX_API=${STATE_PORT}
export RESTREAM_CPUSET=${restream_mask}
export SRT_SINK_CPUSET=${sink_mask}
EOF

  echo "[veth-topology] up: ${VETH_HOST} $(echo "$HOST_ADDR" | cut -d/ -f1) <-> ${NETNS}:${VETH_PEER} $(echo "$PEER_ADDR" | cut -d/ -f1)"
  echo "[veth-topology] restream cpus ${restream_mask}, sink cpus ${sink_mask}"
  echo "[veth-topology] env written to ${ENV_FILE}"
  cat <<EOF
[veth-topology] run the peer inside the namespace:
  source ${ENV_FILE}
  scripts/harness/veth-topology.sh start-peer [srt-sink|udp-drain]
EOF
}

cmd_down() {
  require_root
  if ip netns list | grep -q "^${NETNS}\b"; then
    ip netns del "$NETNS"
  fi
  ip link del "$VETH_HOST" 2>/dev/null || true
  rm -f "$ENV_FILE"
  echo "[veth-topology] down: ${NETNS} and ${VETH_HOST} removed"
}

cmd_status() {
  echo "[veth-topology] netns:"
  ip netns list | sed 's/^/  /' || true
  echo "[veth-topology] ${VETH_HOST}:"
  ip -brief addr show "$VETH_HOST" 2>/dev/null | sed 's/^/  /' || echo "  absent"
  echo "[veth-topology] env file: ${ENV_FILE}"
  [[ -f "$ENV_FILE" ]] && sed 's/^/  /' "$ENV_FILE" || echo "  absent"
}

# Start the peer process inside the namespace on the sink CPUs, with the ports
# and masks from the generated env file. `env` is required: `ip netns exec`
# would otherwise try to execute the assignment as a program.
cmd_start_peer() {
  local mode="${1:-srt-sink}"
  [[ -f "$ENV_FILE" ]] || { echo "[veth-topology] run 'up' first (${ENV_FILE} missing)" >&2; exit 2; }
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  local binary="${WI3_PEER_BIN:-$ROOT_DIR/target/bench/sink-peer/test_harness}"
  [[ -x "$binary" ]] || { echo "[veth-topology] peer binary missing: ${binary}" >&2; exit 2; }
  case "$mode" in
    srt-sink)
      exec sudo -n ip netns exec "$NETNS" env \
        SRT_SINK_PORTS="$SRT_PORT" SRT_SINK_STATE_PORT="$STATE_PORT" \
        SRT_SINK_CPUSET="$SRT_SINK_CPUSET" HARNESS_SRT_SINK_THREADS="${HARNESS_SRT_SINK_THREADS:-4}" \
        HARNESS_SRT_SINK_UDP_BUFFER="${HARNESS_SRT_SINK_UDP_BUFFER:-33554432}" \
        "$binary" srt-sink --no-netns
      ;;
    udp-drain)
      exec sudo -n ip netns exec "$NETNS" env \
        UDP_DRAIN_PORT="${UDP_DRAIN_PORT:-9000}" UDP_DRAIN_STATE_PORT="$STATE_PORT" \
        UDP_DRAIN_CPUSET="$SRT_SINK_CPUSET" \
        "$binary" udp-drain --no-netns
      ;;
    *)
      echo "[veth-topology] unknown peer mode ${mode}; expected srt-sink or udp-drain" >&2
      exit 2
      ;;
  esac
}

case "${1:-}" in
  up) shift; cmd_up "$@" ;;
  down) cmd_down ;;
  status) cmd_status ;;
  start-peer) shift; cmd_start_peer "$@" ;;
  *) usage; exit 2 ;;
esac
