pub mod agent;
pub mod alerts;
pub mod auth;
pub mod file_ingest;
pub mod health;
pub mod hls;
pub mod ingests;
pub mod logs;
pub mod media_library;
pub mod outputs;
pub mod pipelines;
pub mod router;
pub mod settings;
pub mod state;
pub mod static_assets;
pub mod telemetry;

pub use auth::{initialize_auth, initialize_auth_for_test};
pub use router::create_router;
pub use state::{AppState, PortConfig};
pub use static_assets::EmbeddedAssets;
