#!/usr/bin/env bash
# Generate local Claude Code skill registrations from the canonical,
# agent-neutral skill bodies in docs/agent-guidance/skills/.
#
# .claude/ is gitignored; run this once per clone or worktree
# (scripts/agent/worktree.sh runs it automatically). Idempotent — re-run
# after adding a skill or editing skill frontmatter.
#
# Default mode writes small shim files per skill (registration proven across
# Claude Code versions). --symlink instead links .claude/skills at the
# canonical directory: zero drift and one fewer file read per invocation,
# but relies on the skill loader following symlinks.
set -euo pipefail

repo_root="${RESTREAM_REPO_ROOT:-$(git rev-parse --show-toplevel)}"
canon_dir="$repo_root/docs/agent-guidance/skills"
dest_dir="$repo_root/.claude/skills"
shim_marker="generated by scripts/agent/setup-skills.sh"
mode="shim"

case "${1:-}" in
"") ;;
--symlink) mode="symlink" ;;
-h | --help)
    sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
*)
    echo "usage: scripts/agent/setup-skills.sh [--symlink]" >&2
    exit 2
    ;;
esac

[[ -d "$canon_dir" ]] || {
    echo "error: canonical skills not found at $canon_dir" >&2
    exit 1
}

if [[ "$mode" == "symlink" ]]; then
    if [[ -e "$dest_dir" && ! -L "$dest_dir" ]]; then
        # Refuse to delete anything we did not generate.
        stray=$(grep -rL "$shim_marker" "$dest_dir" --include=SKILL.md 2>/dev/null || true)
        if [[ -n "$stray" ]]; then
            echo "error: $dest_dir contains files not generated by this script; move them first:" >&2
            echo "$stray" >&2
            exit 1
        fi
        rm -rf "$dest_dir"
    fi
    mkdir -p "$repo_root/.claude"
    ln -sfn "../docs/agent-guidance/skills" "$dest_dir"
    echo "linked .claude/skills -> docs/agent-guidance/skills"
    exit 0
fi

if [[ -L "$dest_dir" ]]; then
    rm "$dest_dir"
fi
mkdir -p "$dest_dir"

count=0
for skill_md in "$canon_dir"/*/SKILL.md; do
    name="$(basename "$(dirname "$skill_md")")"
    desc_line="$(grep -m1 '^description:' "$skill_md" || true)"
    if [[ -z "$desc_line" ]]; then
        echo "warn: skip $name (no description: frontmatter)" >&2
        continue
    fi
    desc_body="${desc_line#description: }"
    # Keep the shim frontmatter valid YAML: double-quote descriptions unless
    # they already contain double quotes (none of those contain ": ").
    if [[ "$desc_body" != *'"'* ]]; then
        desc_line="description: \"$desc_body\""
    elif [[ "$desc_body" == *': '* ]]; then
        echo "warn: $name description mixes double quotes and ': '; check the shim parses" >&2
    fi
    mkdir -p "$dest_dir/$name"
    printf -- '---\nname: %s\n%s\n---\n\nClaude Code registration shim (%s).\nThe canonical, agent-neutral skill lives at\n[docs/agent-guidance/skills/%s/SKILL.md](../../../docs/agent-guidance/skills/%s/SKILL.md).\n\nRead that file now and follow its instructions exactly.\n' \
        "$name" "$desc_line" "$shim_marker" "$name" "$name" >"$dest_dir/$name/SKILL.md"
    count=$((count + 1))
done

# Prune shims we generated whose canonical skill no longer exists.
for shim_dir in "$dest_dir"/*/; do
    [[ -d "$shim_dir" ]] || continue
    name="$(basename "$shim_dir")"
    if [[ ! -f "$canon_dir/$name/SKILL.md" ]] &&
        grep -q "$shim_marker" "$shim_dir/SKILL.md" 2>/dev/null; then
        rm -rf "$shim_dir"
        echo "pruned stale shim: $name"
    fi
done

echo "generated $count Claude Code skill shims in .claude/skills/"
