#!/usr/bin/env bash
# Fetch a BtbN FFmpeg shared build into the repo native prefix for local/agent
# lint and iteration. This is not a substitute for the release static prefix
# produced by scripts/build/native-deps.sh.
set -euo pipefail

ROOT="${RESTREAM_REPO_ROOT:-$(git rev-parse --show-toplevel)}"
BUILD_ROOT="${RESTREAM_BUILD_ROOT:-$ROOT/.local/build/static}"
PREFIX="$BUILD_ROOT/prefix"
CACHE_DIR="$BUILD_ROOT/btbn-cache"

# Pin to the same major line as scripts/build/native/native-inputs.lock (n8.1.2).
# BtbN's "latest" float for that line ships devel headers + shared libav*.
BTBN_ASSET="${RESTREAM_BTBN_FFMPEG_ASSET:-ffmpeg-n8.1-latest-linux64-gpl-shared-8.1.tar.xz}"
BTBN_URL="${RESTREAM_BTBN_FFMPEG_URL:-https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/$BTBN_ASSET}"

usage() {
    cat <<'EOF'
Usage: scripts/dev/fetch-btbn-ffmpeg.sh

Download a BtbN linux64 gpl-shared FFmpeg build into
.local/build/static/prefix for local cargo check/clippy/test linking.

Writes:
  prefix/.restream-native-link-shared   marker for build.rs shared mode
  .local/build/static/env.sh            PKG_CONFIG / LD_LIBRARY_PATH helpers

Does not replace scripts/build/native-deps.sh for release/static binaries.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi
if [[ $# -gt 0 ]]; then
    usage >&2
    exit 2
fi

for command in curl tar install; do
    command -v "$command" >/dev/null || {
        echo "fetch-btbn-ffmpeg: missing required command: $command" >&2
        exit 1
    }
done

mkdir -p "$CACHE_DIR" "$PREFIX"
ARCHIVE="$CACHE_DIR/$BTBN_ASSET"

if [[ ! -f "$ARCHIVE" ]]; then
    echo "fetch-btbn-ffmpeg: downloading $BTBN_URL"
    curl -fL --retry 4 --retry-delay 2 -o "$ARCHIVE.partial" "$BTBN_URL"
    mv "$ARCHIVE.partial" "$ARCHIVE"
else
    echo "fetch-btbn-ffmpeg: reusing cached $ARCHIVE"
fi

TMP="$(mktemp -d "$CACHE_DIR/extract.XXXXXX")"
cleanup() {
    rm -rf "$TMP"
}
trap cleanup EXIT

tar -xJf "$ARCHIVE" -C "$TMP"
SRC="$(find "$TMP" -mindepth 1 -maxdepth 1 -type d | head -n1)"
if [[ -z "$SRC" || ! -d "$SRC/include" || ! -d "$SRC/lib" ]]; then
    echo "fetch-btbn-ffmpeg: unexpected archive layout in $BTBN_ASSET" >&2
    exit 1
fi

# Replace only the FFmpeg devel tree; leave any co-located static archives alone
# so a half-migrated tree fails loudly instead of silently mixing modes.
rm -rf "$PREFIX/include" "$PREFIX/lib" "$PREFIX/bin"
mkdir -p "$PREFIX"
cp -a "$SRC/include" "$SRC/lib" "$SRC/bin" "$PREFIX/"

# Seed the subprocess ffmpeg path so RustEmbed / extract paths work without a
# full native-deps + frontend prepare. Prefer the real BtbN binary.
mkdir -p "$ROOT/public/bin"
cp -a "$PREFIX/bin/ffmpeg" "$ROOT/public/bin/ffmpeg"
chmod +x "$ROOT/public/bin/ffmpeg"
# Ensure rust-embed's public/ folder exists even before a frontend build.
mkdir -p "$ROOT/public/js"

MARKER="$PREFIX/.restream-native-link-shared"
cat >"$MARKER" <<EOF
source=BtbN/FFmpeg-Builds
asset=$BTBN_ASSET
url=$BTBN_URL
fetched_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

cat >"$BUILD_ROOT/env.sh" <<EOF
# Generated by scripts/dev/fetch-btbn-ffmpeg.sh — local/agent shared FFmpeg.
export RESTREAM_BUILD_ROOT="$BUILD_ROOT"
export RESTREAM_NATIVE_LINK_MODE=shared
export FFMPEG_DIR="$PREFIX"
export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig\${PKG_CONFIG_PATH:+:\$PKG_CONFIG_PATH}"
export LD_LIBRARY_PATH="$PREFIX/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export PATH="$PREFIX/bin\${PATH:+:\$PATH}"
EOF

echo "fetch-btbn-ffmpeg: installed shared FFmpeg into $PREFIX"
echo "fetch-btbn-ffmpeg: source $BUILD_ROOT/env.sh (or rely on build.rs marker detection)"
echo "fetch-btbn-ffmpeg: for release/static builds use scripts/build/native-deps.sh instead"
